
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Floor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Floor
 * 
 */
export type FloorModel = runtime.Types.Result.DefaultSelection<Prisma.$FloorPayload>

export type AggregateFloor = {
  _count: FloorCountAggregateOutputType | null
  _avg: FloorAvgAggregateOutputType | null
  _sum: FloorSumAggregateOutputType | null
  _min: FloorMinAggregateOutputType | null
  _max: FloorMaxAggregateOutputType | null
}

export type FloorAvgAggregateOutputType = {
  level: number | null
}

export type FloorSumAggregateOutputType = {
  level: number | null
}

export type FloorMinAggregateOutputType = {
  id: string | null
  level: number | null
  createdAt: Date | null
  updatedAt: Date | null
  buildingId: string | null
  createdById: string | null
}

export type FloorMaxAggregateOutputType = {
  id: string | null
  level: number | null
  createdAt: Date | null
  updatedAt: Date | null
  buildingId: string | null
  createdById: string | null
}

export type FloorCountAggregateOutputType = {
  id: number
  level: number
  createdAt: number
  updatedAt: number
  buildingId: number
  createdById: number
  _all: number
}


export type FloorAvgAggregateInputType = {
  level?: true
}

export type FloorSumAggregateInputType = {
  level?: true
}

export type FloorMinAggregateInputType = {
  id?: true
  level?: true
  createdAt?: true
  updatedAt?: true
  buildingId?: true
  createdById?: true
}

export type FloorMaxAggregateInputType = {
  id?: true
  level?: true
  createdAt?: true
  updatedAt?: true
  buildingId?: true
  createdById?: true
}

export type FloorCountAggregateInputType = {
  id?: true
  level?: true
  createdAt?: true
  updatedAt?: true
  buildingId?: true
  createdById?: true
  _all?: true
}

export type FloorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Floor to aggregate.
   */
  where?: Prisma.FloorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Floors to fetch.
   */
  orderBy?: Prisma.FloorOrderByWithRelationInput | Prisma.FloorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FloorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Floors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Floors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Floors
  **/
  _count?: true | FloorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FloorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FloorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FloorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FloorMaxAggregateInputType
}

export type GetFloorAggregateType<T extends FloorAggregateArgs> = {
      [P in keyof T & keyof AggregateFloor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFloor[P]>
    : Prisma.GetScalarType<T[P], AggregateFloor[P]>
}




export type FloorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FloorWhereInput
  orderBy?: Prisma.FloorOrderByWithAggregationInput | Prisma.FloorOrderByWithAggregationInput[]
  by: Prisma.FloorScalarFieldEnum[] | Prisma.FloorScalarFieldEnum
  having?: Prisma.FloorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FloorCountAggregateInputType | true
  _avg?: FloorAvgAggregateInputType
  _sum?: FloorSumAggregateInputType
  _min?: FloorMinAggregateInputType
  _max?: FloorMaxAggregateInputType
}

export type FloorGroupByOutputType = {
  id: string
  level: number
  createdAt: Date
  updatedAt: Date
  buildingId: string
  createdById: string
  _count: FloorCountAggregateOutputType | null
  _avg: FloorAvgAggregateOutputType | null
  _sum: FloorSumAggregateOutputType | null
  _min: FloorMinAggregateOutputType | null
  _max: FloorMaxAggregateOutputType | null
}

type GetFloorGroupByPayload<T extends FloorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FloorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FloorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FloorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FloorGroupByOutputType[P]>
      }
    >
  >



export type FloorWhereInput = {
  AND?: Prisma.FloorWhereInput | Prisma.FloorWhereInput[]
  OR?: Prisma.FloorWhereInput[]
  NOT?: Prisma.FloorWhereInput | Prisma.FloorWhereInput[]
  id?: Prisma.StringFilter<"Floor"> | string
  level?: Prisma.IntFilter<"Floor"> | number
  createdAt?: Prisma.DateTimeFilter<"Floor"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Floor"> | Date | string
  buildingId?: Prisma.StringFilter<"Floor"> | string
  createdById?: Prisma.StringFilter<"Floor"> | string
  rooms?: Prisma.RoomListRelationFilter
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type FloorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  rooms?: Prisma.RoomOrderByRelationAggregateInput
  building?: Prisma.BuildingOrderByWithRelationInput
  createdBy?: Prisma.UserOrderByWithRelationInput
}

export type FloorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.FloorWhereInput | Prisma.FloorWhereInput[]
  OR?: Prisma.FloorWhereInput[]
  NOT?: Prisma.FloorWhereInput | Prisma.FloorWhereInput[]
  level?: Prisma.IntFilter<"Floor"> | number
  createdAt?: Prisma.DateTimeFilter<"Floor"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Floor"> | Date | string
  buildingId?: Prisma.StringFilter<"Floor"> | string
  createdById?: Prisma.StringFilter<"Floor"> | string
  rooms?: Prisma.RoomListRelationFilter
  building?: Prisma.XOR<Prisma.BuildingScalarRelationFilter, Prisma.BuildingWhereInput>
  createdBy?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id">

export type FloorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
  _count?: Prisma.FloorCountOrderByAggregateInput
  _avg?: Prisma.FloorAvgOrderByAggregateInput
  _max?: Prisma.FloorMaxOrderByAggregateInput
  _min?: Prisma.FloorMinOrderByAggregateInput
  _sum?: Prisma.FloorSumOrderByAggregateInput
}

export type FloorScalarWhereWithAggregatesInput = {
  AND?: Prisma.FloorScalarWhereWithAggregatesInput | Prisma.FloorScalarWhereWithAggregatesInput[]
  OR?: Prisma.FloorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FloorScalarWhereWithAggregatesInput | Prisma.FloorScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Floor"> | string
  level?: Prisma.IntWithAggregatesFilter<"Floor"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Floor"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Floor"> | Date | string
  buildingId?: Prisma.StringWithAggregatesFilter<"Floor"> | string
  createdById?: Prisma.StringWithAggregatesFilter<"Floor"> | string
}

export type FloorCreateInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  rooms?: Prisma.RoomCreateNestedManyWithoutFloorInput
  building: Prisma.BuildingCreateNestedOneWithoutFloorsInput
  createdBy: Prisma.UserCreateNestedOneWithoutFloorsCreatedInput
}

export type FloorUncheckedCreateInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  buildingId: string
  createdById: string
  rooms?: Prisma.RoomUncheckedCreateNestedManyWithoutFloorInput
}

export type FloorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rooms?: Prisma.RoomUpdateManyWithoutFloorNestedInput
  building?: Prisma.BuildingUpdateOneRequiredWithoutFloorsNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutFloorsCreatedNestedInput
}

export type FloorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
  rooms?: Prisma.RoomUncheckedUpdateManyWithoutFloorNestedInput
}

export type FloorCreateManyInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  buildingId: string
  createdById: string
}

export type FloorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FloorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FloorListRelationFilter = {
  every?: Prisma.FloorWhereInput
  some?: Prisma.FloorWhereInput
  none?: Prisma.FloorWhereInput
}

export type FloorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type FloorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FloorAvgOrderByAggregateInput = {
  level?: Prisma.SortOrder
}

export type FloorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FloorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  level?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  buildingId?: Prisma.SortOrder
  createdById?: Prisma.SortOrder
}

export type FloorSumOrderByAggregateInput = {
  level?: Prisma.SortOrder
}

export type FloorScalarRelationFilter = {
  is?: Prisma.FloorWhereInput
  isNot?: Prisma.FloorWhereInput
}

export type FloorCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutCreatedByInput, Prisma.FloorUncheckedCreateWithoutCreatedByInput> | Prisma.FloorCreateWithoutCreatedByInput[] | Prisma.FloorUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutCreatedByInput | Prisma.FloorCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.FloorCreateManyCreatedByInputEnvelope
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
}

export type FloorUncheckedCreateNestedManyWithoutCreatedByInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutCreatedByInput, Prisma.FloorUncheckedCreateWithoutCreatedByInput> | Prisma.FloorCreateWithoutCreatedByInput[] | Prisma.FloorUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutCreatedByInput | Prisma.FloorCreateOrConnectWithoutCreatedByInput[]
  createMany?: Prisma.FloorCreateManyCreatedByInputEnvelope
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
}

export type FloorUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutCreatedByInput, Prisma.FloorUncheckedCreateWithoutCreatedByInput> | Prisma.FloorCreateWithoutCreatedByInput[] | Prisma.FloorUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutCreatedByInput | Prisma.FloorCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.FloorUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.FloorUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.FloorCreateManyCreatedByInputEnvelope
  set?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  disconnect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  delete?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  update?: Prisma.FloorUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.FloorUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.FloorUpdateManyWithWhereWithoutCreatedByInput | Prisma.FloorUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.FloorScalarWhereInput | Prisma.FloorScalarWhereInput[]
}

export type FloorUncheckedUpdateManyWithoutCreatedByNestedInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutCreatedByInput, Prisma.FloorUncheckedCreateWithoutCreatedByInput> | Prisma.FloorCreateWithoutCreatedByInput[] | Prisma.FloorUncheckedCreateWithoutCreatedByInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutCreatedByInput | Prisma.FloorCreateOrConnectWithoutCreatedByInput[]
  upsert?: Prisma.FloorUpsertWithWhereUniqueWithoutCreatedByInput | Prisma.FloorUpsertWithWhereUniqueWithoutCreatedByInput[]
  createMany?: Prisma.FloorCreateManyCreatedByInputEnvelope
  set?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  disconnect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  delete?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  update?: Prisma.FloorUpdateWithWhereUniqueWithoutCreatedByInput | Prisma.FloorUpdateWithWhereUniqueWithoutCreatedByInput[]
  updateMany?: Prisma.FloorUpdateManyWithWhereWithoutCreatedByInput | Prisma.FloorUpdateManyWithWhereWithoutCreatedByInput[]
  deleteMany?: Prisma.FloorScalarWhereInput | Prisma.FloorScalarWhereInput[]
}

export type FloorCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutBuildingInput, Prisma.FloorUncheckedCreateWithoutBuildingInput> | Prisma.FloorCreateWithoutBuildingInput[] | Prisma.FloorUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutBuildingInput | Prisma.FloorCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.FloorCreateManyBuildingInputEnvelope
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
}

export type FloorUncheckedCreateNestedManyWithoutBuildingInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutBuildingInput, Prisma.FloorUncheckedCreateWithoutBuildingInput> | Prisma.FloorCreateWithoutBuildingInput[] | Prisma.FloorUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutBuildingInput | Prisma.FloorCreateOrConnectWithoutBuildingInput[]
  createMany?: Prisma.FloorCreateManyBuildingInputEnvelope
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
}

export type FloorUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutBuildingInput, Prisma.FloorUncheckedCreateWithoutBuildingInput> | Prisma.FloorCreateWithoutBuildingInput[] | Prisma.FloorUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutBuildingInput | Prisma.FloorCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.FloorUpsertWithWhereUniqueWithoutBuildingInput | Prisma.FloorUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.FloorCreateManyBuildingInputEnvelope
  set?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  disconnect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  delete?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  update?: Prisma.FloorUpdateWithWhereUniqueWithoutBuildingInput | Prisma.FloorUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.FloorUpdateManyWithWhereWithoutBuildingInput | Prisma.FloorUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.FloorScalarWhereInput | Prisma.FloorScalarWhereInput[]
}

export type FloorUncheckedUpdateManyWithoutBuildingNestedInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutBuildingInput, Prisma.FloorUncheckedCreateWithoutBuildingInput> | Prisma.FloorCreateWithoutBuildingInput[] | Prisma.FloorUncheckedCreateWithoutBuildingInput[]
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutBuildingInput | Prisma.FloorCreateOrConnectWithoutBuildingInput[]
  upsert?: Prisma.FloorUpsertWithWhereUniqueWithoutBuildingInput | Prisma.FloorUpsertWithWhereUniqueWithoutBuildingInput[]
  createMany?: Prisma.FloorCreateManyBuildingInputEnvelope
  set?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  disconnect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  delete?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  connect?: Prisma.FloorWhereUniqueInput | Prisma.FloorWhereUniqueInput[]
  update?: Prisma.FloorUpdateWithWhereUniqueWithoutBuildingInput | Prisma.FloorUpdateWithWhereUniqueWithoutBuildingInput[]
  updateMany?: Prisma.FloorUpdateManyWithWhereWithoutBuildingInput | Prisma.FloorUpdateManyWithWhereWithoutBuildingInput[]
  deleteMany?: Prisma.FloorScalarWhereInput | Prisma.FloorScalarWhereInput[]
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FloorCreateNestedOneWithoutRoomsInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutRoomsInput, Prisma.FloorUncheckedCreateWithoutRoomsInput>
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutRoomsInput
  connect?: Prisma.FloorWhereUniqueInput
}

export type FloorUpdateOneRequiredWithoutRoomsNestedInput = {
  create?: Prisma.XOR<Prisma.FloorCreateWithoutRoomsInput, Prisma.FloorUncheckedCreateWithoutRoomsInput>
  connectOrCreate?: Prisma.FloorCreateOrConnectWithoutRoomsInput
  upsert?: Prisma.FloorUpsertWithoutRoomsInput
  connect?: Prisma.FloorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FloorUpdateToOneWithWhereWithoutRoomsInput, Prisma.FloorUpdateWithoutRoomsInput>, Prisma.FloorUncheckedUpdateWithoutRoomsInput>
}

export type FloorCreateWithoutCreatedByInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  rooms?: Prisma.RoomCreateNestedManyWithoutFloorInput
  building: Prisma.BuildingCreateNestedOneWithoutFloorsInput
}

export type FloorUncheckedCreateWithoutCreatedByInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  buildingId: string
  rooms?: Prisma.RoomUncheckedCreateNestedManyWithoutFloorInput
}

export type FloorCreateOrConnectWithoutCreatedByInput = {
  where: Prisma.FloorWhereUniqueInput
  create: Prisma.XOR<Prisma.FloorCreateWithoutCreatedByInput, Prisma.FloorUncheckedCreateWithoutCreatedByInput>
}

export type FloorCreateManyCreatedByInputEnvelope = {
  data: Prisma.FloorCreateManyCreatedByInput | Prisma.FloorCreateManyCreatedByInput[]
  skipDuplicates?: boolean
}

export type FloorUpsertWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.FloorWhereUniqueInput
  update: Prisma.XOR<Prisma.FloorUpdateWithoutCreatedByInput, Prisma.FloorUncheckedUpdateWithoutCreatedByInput>
  create: Prisma.XOR<Prisma.FloorCreateWithoutCreatedByInput, Prisma.FloorUncheckedCreateWithoutCreatedByInput>
}

export type FloorUpdateWithWhereUniqueWithoutCreatedByInput = {
  where: Prisma.FloorWhereUniqueInput
  data: Prisma.XOR<Prisma.FloorUpdateWithoutCreatedByInput, Prisma.FloorUncheckedUpdateWithoutCreatedByInput>
}

export type FloorUpdateManyWithWhereWithoutCreatedByInput = {
  where: Prisma.FloorScalarWhereInput
  data: Prisma.XOR<Prisma.FloorUpdateManyMutationInput, Prisma.FloorUncheckedUpdateManyWithoutCreatedByInput>
}

export type FloorScalarWhereInput = {
  AND?: Prisma.FloorScalarWhereInput | Prisma.FloorScalarWhereInput[]
  OR?: Prisma.FloorScalarWhereInput[]
  NOT?: Prisma.FloorScalarWhereInput | Prisma.FloorScalarWhereInput[]
  id?: Prisma.StringFilter<"Floor"> | string
  level?: Prisma.IntFilter<"Floor"> | number
  createdAt?: Prisma.DateTimeFilter<"Floor"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Floor"> | Date | string
  buildingId?: Prisma.StringFilter<"Floor"> | string
  createdById?: Prisma.StringFilter<"Floor"> | string
}

export type FloorCreateWithoutBuildingInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  rooms?: Prisma.RoomCreateNestedManyWithoutFloorInput
  createdBy: Prisma.UserCreateNestedOneWithoutFloorsCreatedInput
}

export type FloorUncheckedCreateWithoutBuildingInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
  rooms?: Prisma.RoomUncheckedCreateNestedManyWithoutFloorInput
}

export type FloorCreateOrConnectWithoutBuildingInput = {
  where: Prisma.FloorWhereUniqueInput
  create: Prisma.XOR<Prisma.FloorCreateWithoutBuildingInput, Prisma.FloorUncheckedCreateWithoutBuildingInput>
}

export type FloorCreateManyBuildingInputEnvelope = {
  data: Prisma.FloorCreateManyBuildingInput | Prisma.FloorCreateManyBuildingInput[]
  skipDuplicates?: boolean
}

export type FloorUpsertWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.FloorWhereUniqueInput
  update: Prisma.XOR<Prisma.FloorUpdateWithoutBuildingInput, Prisma.FloorUncheckedUpdateWithoutBuildingInput>
  create: Prisma.XOR<Prisma.FloorCreateWithoutBuildingInput, Prisma.FloorUncheckedCreateWithoutBuildingInput>
}

export type FloorUpdateWithWhereUniqueWithoutBuildingInput = {
  where: Prisma.FloorWhereUniqueInput
  data: Prisma.XOR<Prisma.FloorUpdateWithoutBuildingInput, Prisma.FloorUncheckedUpdateWithoutBuildingInput>
}

export type FloorUpdateManyWithWhereWithoutBuildingInput = {
  where: Prisma.FloorScalarWhereInput
  data: Prisma.XOR<Prisma.FloorUpdateManyMutationInput, Prisma.FloorUncheckedUpdateManyWithoutBuildingInput>
}

export type FloorCreateWithoutRoomsInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  building: Prisma.BuildingCreateNestedOneWithoutFloorsInput
  createdBy: Prisma.UserCreateNestedOneWithoutFloorsCreatedInput
}

export type FloorUncheckedCreateWithoutRoomsInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  buildingId: string
  createdById: string
}

export type FloorCreateOrConnectWithoutRoomsInput = {
  where: Prisma.FloorWhereUniqueInput
  create: Prisma.XOR<Prisma.FloorCreateWithoutRoomsInput, Prisma.FloorUncheckedCreateWithoutRoomsInput>
}

export type FloorUpsertWithoutRoomsInput = {
  update: Prisma.XOR<Prisma.FloorUpdateWithoutRoomsInput, Prisma.FloorUncheckedUpdateWithoutRoomsInput>
  create: Prisma.XOR<Prisma.FloorCreateWithoutRoomsInput, Prisma.FloorUncheckedCreateWithoutRoomsInput>
  where?: Prisma.FloorWhereInput
}

export type FloorUpdateToOneWithWhereWithoutRoomsInput = {
  where?: Prisma.FloorWhereInput
  data: Prisma.XOR<Prisma.FloorUpdateWithoutRoomsInput, Prisma.FloorUncheckedUpdateWithoutRoomsInput>
}

export type FloorUpdateWithoutRoomsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  building?: Prisma.BuildingUpdateOneRequiredWithoutFloorsNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutFloorsCreatedNestedInput
}

export type FloorUncheckedUpdateWithoutRoomsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FloorCreateManyCreatedByInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  buildingId: string
}

export type FloorUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rooms?: Prisma.RoomUpdateManyWithoutFloorNestedInput
  building?: Prisma.BuildingUpdateOneRequiredWithoutFloorsNestedInput
}

export type FloorUncheckedUpdateWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
  rooms?: Prisma.RoomUncheckedUpdateManyWithoutFloorNestedInput
}

export type FloorUncheckedUpdateManyWithoutCreatedByInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  buildingId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FloorCreateManyBuildingInput = {
  id?: string
  level: number
  createdAt?: Date | string
  updatedAt?: Date | string
  createdById: string
}

export type FloorUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rooms?: Prisma.RoomUpdateManyWithoutFloorNestedInput
  createdBy?: Prisma.UserUpdateOneRequiredWithoutFloorsCreatedNestedInput
}

export type FloorUncheckedUpdateWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
  rooms?: Prisma.RoomUncheckedUpdateManyWithoutFloorNestedInput
}

export type FloorUncheckedUpdateManyWithoutBuildingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  level?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdById?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type FloorCountOutputType
 */

export type FloorCountOutputType = {
  rooms: number
}

export type FloorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rooms?: boolean | FloorCountOutputTypeCountRoomsArgs
}

/**
 * FloorCountOutputType without action
 */
export type FloorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FloorCountOutputType
   */
  select?: Prisma.FloorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FloorCountOutputType without action
 */
export type FloorCountOutputTypeCountRoomsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RoomWhereInput
}


export type FloorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  buildingId?: boolean
  createdById?: boolean
  rooms?: boolean | Prisma.Floor$roomsArgs<ExtArgs>
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.FloorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["floor"]>

export type FloorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  buildingId?: boolean
  createdById?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["floor"]>

export type FloorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  buildingId?: boolean
  createdById?: boolean
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["floor"]>

export type FloorSelectScalar = {
  id?: boolean
  level?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  buildingId?: boolean
  createdById?: boolean
}

export type FloorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "level" | "createdAt" | "updatedAt" | "buildingId" | "createdById", ExtArgs["result"]["floor"]>
export type FloorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rooms?: boolean | Prisma.Floor$roomsArgs<ExtArgs>
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.FloorCountOutputTypeDefaultArgs<ExtArgs>
}
export type FloorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type FloorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  building?: boolean | Prisma.BuildingDefaultArgs<ExtArgs>
  createdBy?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $FloorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Floor"
  objects: {
    rooms: Prisma.$RoomPayload<ExtArgs>[]
    building: Prisma.$BuildingPayload<ExtArgs>
    createdBy: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    level: number
    createdAt: Date
    updatedAt: Date
    buildingId: string
    createdById: string
  }, ExtArgs["result"]["floor"]>
  composites: {}
}

export type FloorGetPayload<S extends boolean | null | undefined | FloorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FloorPayload, S>

export type FloorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FloorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FloorCountAggregateInputType | true
  }

export interface FloorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Floor'], meta: { name: 'Floor' } }
  /**
   * Find zero or one Floor that matches the filter.
   * @param {FloorFindUniqueArgs} args - Arguments to find a Floor
   * @example
   * // Get one Floor
   * const floor = await prisma.floor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FloorFindUniqueArgs>(args: Prisma.SelectSubset<T, FloorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Floor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FloorFindUniqueOrThrowArgs} args - Arguments to find a Floor
   * @example
   * // Get one Floor
   * const floor = await prisma.floor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FloorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FloorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Floor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloorFindFirstArgs} args - Arguments to find a Floor
   * @example
   * // Get one Floor
   * const floor = await prisma.floor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FloorFindFirstArgs>(args?: Prisma.SelectSubset<T, FloorFindFirstArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Floor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloorFindFirstOrThrowArgs} args - Arguments to find a Floor
   * @example
   * // Get one Floor
   * const floor = await prisma.floor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FloorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FloorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Floors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Floors
   * const floors = await prisma.floor.findMany()
   * 
   * // Get first 10 Floors
   * const floors = await prisma.floor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const floorWithIdOnly = await prisma.floor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FloorFindManyArgs>(args?: Prisma.SelectSubset<T, FloorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Floor.
   * @param {FloorCreateArgs} args - Arguments to create a Floor.
   * @example
   * // Create one Floor
   * const Floor = await prisma.floor.create({
   *   data: {
   *     // ... data to create a Floor
   *   }
   * })
   * 
   */
  create<T extends FloorCreateArgs>(args: Prisma.SelectSubset<T, FloorCreateArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Floors.
   * @param {FloorCreateManyArgs} args - Arguments to create many Floors.
   * @example
   * // Create many Floors
   * const floor = await prisma.floor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FloorCreateManyArgs>(args?: Prisma.SelectSubset<T, FloorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Floors and returns the data saved in the database.
   * @param {FloorCreateManyAndReturnArgs} args - Arguments to create many Floors.
   * @example
   * // Create many Floors
   * const floor = await prisma.floor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Floors and only return the `id`
   * const floorWithIdOnly = await prisma.floor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FloorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FloorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Floor.
   * @param {FloorDeleteArgs} args - Arguments to delete one Floor.
   * @example
   * // Delete one Floor
   * const Floor = await prisma.floor.delete({
   *   where: {
   *     // ... filter to delete one Floor
   *   }
   * })
   * 
   */
  delete<T extends FloorDeleteArgs>(args: Prisma.SelectSubset<T, FloorDeleteArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Floor.
   * @param {FloorUpdateArgs} args - Arguments to update one Floor.
   * @example
   * // Update one Floor
   * const floor = await prisma.floor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FloorUpdateArgs>(args: Prisma.SelectSubset<T, FloorUpdateArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Floors.
   * @param {FloorDeleteManyArgs} args - Arguments to filter Floors to delete.
   * @example
   * // Delete a few Floors
   * const { count } = await prisma.floor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FloorDeleteManyArgs>(args?: Prisma.SelectSubset<T, FloorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Floors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Floors
   * const floor = await prisma.floor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FloorUpdateManyArgs>(args: Prisma.SelectSubset<T, FloorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Floors and returns the data updated in the database.
   * @param {FloorUpdateManyAndReturnArgs} args - Arguments to update many Floors.
   * @example
   * // Update many Floors
   * const floor = await prisma.floor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Floors and only return the `id`
   * const floorWithIdOnly = await prisma.floor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FloorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FloorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Floor.
   * @param {FloorUpsertArgs} args - Arguments to update or create a Floor.
   * @example
   * // Update or create a Floor
   * const floor = await prisma.floor.upsert({
   *   create: {
   *     // ... data to create a Floor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Floor we want to update
   *   }
   * })
   */
  upsert<T extends FloorUpsertArgs>(args: Prisma.SelectSubset<T, FloorUpsertArgs<ExtArgs>>): Prisma.Prisma__FloorClient<runtime.Types.Result.GetResult<Prisma.$FloorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Floors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloorCountArgs} args - Arguments to filter Floors to count.
   * @example
   * // Count the number of Floors
   * const count = await prisma.floor.count({
   *   where: {
   *     // ... the filter for the Floors we want to count
   *   }
   * })
  **/
  count<T extends FloorCountArgs>(
    args?: Prisma.Subset<T, FloorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FloorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Floor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FloorAggregateArgs>(args: Prisma.Subset<T, FloorAggregateArgs>): Prisma.PrismaPromise<GetFloorAggregateType<T>>

  /**
   * Group by Floor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FloorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FloorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FloorGroupByArgs['orderBy'] }
      : { orderBy?: FloorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FloorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFloorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Floor model
 */
readonly fields: FloorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Floor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FloorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  rooms<T extends Prisma.Floor$roomsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Floor$roomsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RoomPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  building<T extends Prisma.BuildingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BuildingDefaultArgs<ExtArgs>>): Prisma.Prisma__BuildingClient<runtime.Types.Result.GetResult<Prisma.$BuildingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  createdBy<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Floor model
 */
export interface FloorFieldRefs {
  readonly id: Prisma.FieldRef<"Floor", 'String'>
  readonly level: Prisma.FieldRef<"Floor", 'Int'>
  readonly createdAt: Prisma.FieldRef<"Floor", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Floor", 'DateTime'>
  readonly buildingId: Prisma.FieldRef<"Floor", 'String'>
  readonly createdById: Prisma.FieldRef<"Floor", 'String'>
}
    

// Custom InputTypes
/**
 * Floor findUnique
 */
export type FloorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * Filter, which Floor to fetch.
   */
  where: Prisma.FloorWhereUniqueInput
}

/**
 * Floor findUniqueOrThrow
 */
export type FloorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * Filter, which Floor to fetch.
   */
  where: Prisma.FloorWhereUniqueInput
}

/**
 * Floor findFirst
 */
export type FloorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * Filter, which Floor to fetch.
   */
  where?: Prisma.FloorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Floors to fetch.
   */
  orderBy?: Prisma.FloorOrderByWithRelationInput | Prisma.FloorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Floors.
   */
  cursor?: Prisma.FloorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Floors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Floors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Floors.
   */
  distinct?: Prisma.FloorScalarFieldEnum | Prisma.FloorScalarFieldEnum[]
}

/**
 * Floor findFirstOrThrow
 */
export type FloorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * Filter, which Floor to fetch.
   */
  where?: Prisma.FloorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Floors to fetch.
   */
  orderBy?: Prisma.FloorOrderByWithRelationInput | Prisma.FloorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Floors.
   */
  cursor?: Prisma.FloorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Floors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Floors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Floors.
   */
  distinct?: Prisma.FloorScalarFieldEnum | Prisma.FloorScalarFieldEnum[]
}

/**
 * Floor findMany
 */
export type FloorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * Filter, which Floors to fetch.
   */
  where?: Prisma.FloorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Floors to fetch.
   */
  orderBy?: Prisma.FloorOrderByWithRelationInput | Prisma.FloorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Floors.
   */
  cursor?: Prisma.FloorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Floors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Floors.
   */
  skip?: number
  distinct?: Prisma.FloorScalarFieldEnum | Prisma.FloorScalarFieldEnum[]
}

/**
 * Floor create
 */
export type FloorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * The data needed to create a Floor.
   */
  data: Prisma.XOR<Prisma.FloorCreateInput, Prisma.FloorUncheckedCreateInput>
}

/**
 * Floor createMany
 */
export type FloorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Floors.
   */
  data: Prisma.FloorCreateManyInput | Prisma.FloorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Floor createManyAndReturn
 */
export type FloorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * The data used to create many Floors.
   */
  data: Prisma.FloorCreateManyInput | Prisma.FloorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Floor update
 */
export type FloorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * The data needed to update a Floor.
   */
  data: Prisma.XOR<Prisma.FloorUpdateInput, Prisma.FloorUncheckedUpdateInput>
  /**
   * Choose, which Floor to update.
   */
  where: Prisma.FloorWhereUniqueInput
}

/**
 * Floor updateMany
 */
export type FloorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Floors.
   */
  data: Prisma.XOR<Prisma.FloorUpdateManyMutationInput, Prisma.FloorUncheckedUpdateManyInput>
  /**
   * Filter which Floors to update
   */
  where?: Prisma.FloorWhereInput
  /**
   * Limit how many Floors to update.
   */
  limit?: number
}

/**
 * Floor updateManyAndReturn
 */
export type FloorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * The data used to update Floors.
   */
  data: Prisma.XOR<Prisma.FloorUpdateManyMutationInput, Prisma.FloorUncheckedUpdateManyInput>
  /**
   * Filter which Floors to update
   */
  where?: Prisma.FloorWhereInput
  /**
   * Limit how many Floors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Floor upsert
 */
export type FloorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * The filter to search for the Floor to update in case it exists.
   */
  where: Prisma.FloorWhereUniqueInput
  /**
   * In case the Floor found by the `where` argument doesn't exist, create a new Floor with this data.
   */
  create: Prisma.XOR<Prisma.FloorCreateInput, Prisma.FloorUncheckedCreateInput>
  /**
   * In case the Floor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FloorUpdateInput, Prisma.FloorUncheckedUpdateInput>
}

/**
 * Floor delete
 */
export type FloorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
  /**
   * Filter which Floor to delete.
   */
  where: Prisma.FloorWhereUniqueInput
}

/**
 * Floor deleteMany
 */
export type FloorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Floors to delete
   */
  where?: Prisma.FloorWhereInput
  /**
   * Limit how many Floors to delete.
   */
  limit?: number
}

/**
 * Floor.rooms
 */
export type Floor$roomsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Room
   */
  select?: Prisma.RoomSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Room
   */
  omit?: Prisma.RoomOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RoomInclude<ExtArgs> | null
  where?: Prisma.RoomWhereInput
  orderBy?: Prisma.RoomOrderByWithRelationInput | Prisma.RoomOrderByWithRelationInput[]
  cursor?: Prisma.RoomWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RoomScalarFieldEnum | Prisma.RoomScalarFieldEnum[]
}

/**
 * Floor without action
 */
export type FloorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Floor
   */
  select?: Prisma.FloorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Floor
   */
  omit?: Prisma.FloorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FloorInclude<ExtArgs> | null
}
