
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `InstructionSet` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model InstructionSet
 * 
 */
export type InstructionSetModel = runtime.Types.Result.DefaultSelection<Prisma.$InstructionSetPayload>

export type AggregateInstructionSet = {
  _count: InstructionSetCountAggregateOutputType | null
  _min: InstructionSetMinAggregateOutputType | null
  _max: InstructionSetMaxAggregateOutputType | null
}

export type InstructionSetMinAggregateOutputType = {
  id: string | null
  pathId: string | null
}

export type InstructionSetMaxAggregateOutputType = {
  id: string | null
  pathId: string | null
}

export type InstructionSetCountAggregateOutputType = {
  id: number
  pathId: number
  descriptiveInstructions: number
  conciseInstructions: number
  _all: number
}


export type InstructionSetMinAggregateInputType = {
  id?: true
  pathId?: true
}

export type InstructionSetMaxAggregateInputType = {
  id?: true
  pathId?: true
}

export type InstructionSetCountAggregateInputType = {
  id?: true
  pathId?: true
  descriptiveInstructions?: true
  conciseInstructions?: true
  _all?: true
}

export type InstructionSetAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InstructionSet to aggregate.
   */
  where?: Prisma.InstructionSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstructionSets to fetch.
   */
  orderBy?: Prisma.InstructionSetOrderByWithRelationInput | Prisma.InstructionSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.InstructionSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstructionSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstructionSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned InstructionSets
  **/
  _count?: true | InstructionSetCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: InstructionSetMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: InstructionSetMaxAggregateInputType
}

export type GetInstructionSetAggregateType<T extends InstructionSetAggregateArgs> = {
      [P in keyof T & keyof AggregateInstructionSet]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateInstructionSet[P]>
    : Prisma.GetScalarType<T[P], AggregateInstructionSet[P]>
}




export type InstructionSetGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.InstructionSetWhereInput
  orderBy?: Prisma.InstructionSetOrderByWithAggregationInput | Prisma.InstructionSetOrderByWithAggregationInput[]
  by: Prisma.InstructionSetScalarFieldEnum[] | Prisma.InstructionSetScalarFieldEnum
  having?: Prisma.InstructionSetScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: InstructionSetCountAggregateInputType | true
  _min?: InstructionSetMinAggregateInputType
  _max?: InstructionSetMaxAggregateInputType
}

export type InstructionSetGroupByOutputType = {
  id: string
  pathId: string
  descriptiveInstructions: string[]
  conciseInstructions: string[]
  _count: InstructionSetCountAggregateOutputType | null
  _min: InstructionSetMinAggregateOutputType | null
  _max: InstructionSetMaxAggregateOutputType | null
}

type GetInstructionSetGroupByPayload<T extends InstructionSetGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<InstructionSetGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof InstructionSetGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], InstructionSetGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], InstructionSetGroupByOutputType[P]>
      }
    >
  >



export type InstructionSetWhereInput = {
  AND?: Prisma.InstructionSetWhereInput | Prisma.InstructionSetWhereInput[]
  OR?: Prisma.InstructionSetWhereInput[]
  NOT?: Prisma.InstructionSetWhereInput | Prisma.InstructionSetWhereInput[]
  id?: Prisma.StringFilter<"InstructionSet"> | string
  pathId?: Prisma.StringFilter<"InstructionSet"> | string
  descriptiveInstructions?: Prisma.StringNullableListFilter<"InstructionSet">
  conciseInstructions?: Prisma.StringNullableListFilter<"InstructionSet">
  path?: Prisma.XOR<Prisma.PathScalarRelationFilter, Prisma.PathWhereInput>
}

export type InstructionSetOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
  descriptiveInstructions?: Prisma.SortOrder
  conciseInstructions?: Prisma.SortOrder
  path?: Prisma.PathOrderByWithRelationInput
}

export type InstructionSetWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  pathId?: string
  AND?: Prisma.InstructionSetWhereInput | Prisma.InstructionSetWhereInput[]
  OR?: Prisma.InstructionSetWhereInput[]
  NOT?: Prisma.InstructionSetWhereInput | Prisma.InstructionSetWhereInput[]
  descriptiveInstructions?: Prisma.StringNullableListFilter<"InstructionSet">
  conciseInstructions?: Prisma.StringNullableListFilter<"InstructionSet">
  path?: Prisma.XOR<Prisma.PathScalarRelationFilter, Prisma.PathWhereInput>
}, "id" | "pathId">

export type InstructionSetOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
  descriptiveInstructions?: Prisma.SortOrder
  conciseInstructions?: Prisma.SortOrder
  _count?: Prisma.InstructionSetCountOrderByAggregateInput
  _max?: Prisma.InstructionSetMaxOrderByAggregateInput
  _min?: Prisma.InstructionSetMinOrderByAggregateInput
}

export type InstructionSetScalarWhereWithAggregatesInput = {
  AND?: Prisma.InstructionSetScalarWhereWithAggregatesInput | Prisma.InstructionSetScalarWhereWithAggregatesInput[]
  OR?: Prisma.InstructionSetScalarWhereWithAggregatesInput[]
  NOT?: Prisma.InstructionSetScalarWhereWithAggregatesInput | Prisma.InstructionSetScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"InstructionSet"> | string
  pathId?: Prisma.StringWithAggregatesFilter<"InstructionSet"> | string
  descriptiveInstructions?: Prisma.StringNullableListFilter<"InstructionSet">
  conciseInstructions?: Prisma.StringNullableListFilter<"InstructionSet">
}

export type InstructionSetCreateInput = {
  id?: string
  descriptiveInstructions?: Prisma.InstructionSetCreatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetCreateconciseInstructionsInput | string[]
  path: Prisma.PathCreateNestedOneWithoutInstructionSetInput
}

export type InstructionSetUncheckedCreateInput = {
  id?: string
  pathId: string
  descriptiveInstructions?: Prisma.InstructionSetCreatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetCreateconciseInstructionsInput | string[]
}

export type InstructionSetUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  descriptiveInstructions?: Prisma.InstructionSetUpdatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetUpdateconciseInstructionsInput | string[]
  path?: Prisma.PathUpdateOneRequiredWithoutInstructionSetNestedInput
}

export type InstructionSetUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathId?: Prisma.StringFieldUpdateOperationsInput | string
  descriptiveInstructions?: Prisma.InstructionSetUpdatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetUpdateconciseInstructionsInput | string[]
}

export type InstructionSetCreateManyInput = {
  id?: string
  pathId: string
  descriptiveInstructions?: Prisma.InstructionSetCreatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetCreateconciseInstructionsInput | string[]
}

export type InstructionSetUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  descriptiveInstructions?: Prisma.InstructionSetUpdatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetUpdateconciseInstructionsInput | string[]
}

export type InstructionSetUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  pathId?: Prisma.StringFieldUpdateOperationsInput | string
  descriptiveInstructions?: Prisma.InstructionSetUpdatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetUpdateconciseInstructionsInput | string[]
}

export type InstructionSetNullableScalarRelationFilter = {
  is?: Prisma.InstructionSetWhereInput | null
  isNot?: Prisma.InstructionSetWhereInput | null
}

export type StringNullableListFilter<$PrismaModel = never> = {
  equals?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  has?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  hasEvery?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  hasSome?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type InstructionSetCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
  descriptiveInstructions?: Prisma.SortOrder
  conciseInstructions?: Prisma.SortOrder
}

export type InstructionSetMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
}

export type InstructionSetMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
}

export type InstructionSetCreateNestedOneWithoutPathInput = {
  create?: Prisma.XOR<Prisma.InstructionSetCreateWithoutPathInput, Prisma.InstructionSetUncheckedCreateWithoutPathInput>
  connectOrCreate?: Prisma.InstructionSetCreateOrConnectWithoutPathInput
  connect?: Prisma.InstructionSetWhereUniqueInput
}

export type InstructionSetUncheckedCreateNestedOneWithoutPathInput = {
  create?: Prisma.XOR<Prisma.InstructionSetCreateWithoutPathInput, Prisma.InstructionSetUncheckedCreateWithoutPathInput>
  connectOrCreate?: Prisma.InstructionSetCreateOrConnectWithoutPathInput
  connect?: Prisma.InstructionSetWhereUniqueInput
}

export type InstructionSetUpdateOneWithoutPathNestedInput = {
  create?: Prisma.XOR<Prisma.InstructionSetCreateWithoutPathInput, Prisma.InstructionSetUncheckedCreateWithoutPathInput>
  connectOrCreate?: Prisma.InstructionSetCreateOrConnectWithoutPathInput
  upsert?: Prisma.InstructionSetUpsertWithoutPathInput
  disconnect?: Prisma.InstructionSetWhereInput | boolean
  delete?: Prisma.InstructionSetWhereInput | boolean
  connect?: Prisma.InstructionSetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InstructionSetUpdateToOneWithWhereWithoutPathInput, Prisma.InstructionSetUpdateWithoutPathInput>, Prisma.InstructionSetUncheckedUpdateWithoutPathInput>
}

export type InstructionSetUncheckedUpdateOneWithoutPathNestedInput = {
  create?: Prisma.XOR<Prisma.InstructionSetCreateWithoutPathInput, Prisma.InstructionSetUncheckedCreateWithoutPathInput>
  connectOrCreate?: Prisma.InstructionSetCreateOrConnectWithoutPathInput
  upsert?: Prisma.InstructionSetUpsertWithoutPathInput
  disconnect?: Prisma.InstructionSetWhereInput | boolean
  delete?: Prisma.InstructionSetWhereInput | boolean
  connect?: Prisma.InstructionSetWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.InstructionSetUpdateToOneWithWhereWithoutPathInput, Prisma.InstructionSetUpdateWithoutPathInput>, Prisma.InstructionSetUncheckedUpdateWithoutPathInput>
}

export type InstructionSetCreatedescriptiveInstructionsInput = {
  set: string[]
}

export type InstructionSetCreateconciseInstructionsInput = {
  set: string[]
}

export type InstructionSetUpdatedescriptiveInstructionsInput = {
  set?: string[]
  push?: string | string[]
}

export type InstructionSetUpdateconciseInstructionsInput = {
  set?: string[]
  push?: string | string[]
}

export type InstructionSetCreateWithoutPathInput = {
  id?: string
  descriptiveInstructions?: Prisma.InstructionSetCreatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetCreateconciseInstructionsInput | string[]
}

export type InstructionSetUncheckedCreateWithoutPathInput = {
  id?: string
  descriptiveInstructions?: Prisma.InstructionSetCreatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetCreateconciseInstructionsInput | string[]
}

export type InstructionSetCreateOrConnectWithoutPathInput = {
  where: Prisma.InstructionSetWhereUniqueInput
  create: Prisma.XOR<Prisma.InstructionSetCreateWithoutPathInput, Prisma.InstructionSetUncheckedCreateWithoutPathInput>
}

export type InstructionSetUpsertWithoutPathInput = {
  update: Prisma.XOR<Prisma.InstructionSetUpdateWithoutPathInput, Prisma.InstructionSetUncheckedUpdateWithoutPathInput>
  create: Prisma.XOR<Prisma.InstructionSetCreateWithoutPathInput, Prisma.InstructionSetUncheckedCreateWithoutPathInput>
  where?: Prisma.InstructionSetWhereInput
}

export type InstructionSetUpdateToOneWithWhereWithoutPathInput = {
  where?: Prisma.InstructionSetWhereInput
  data: Prisma.XOR<Prisma.InstructionSetUpdateWithoutPathInput, Prisma.InstructionSetUncheckedUpdateWithoutPathInput>
}

export type InstructionSetUpdateWithoutPathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  descriptiveInstructions?: Prisma.InstructionSetUpdatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetUpdateconciseInstructionsInput | string[]
}

export type InstructionSetUncheckedUpdateWithoutPathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  descriptiveInstructions?: Prisma.InstructionSetUpdatedescriptiveInstructionsInput | string[]
  conciseInstructions?: Prisma.InstructionSetUpdateconciseInstructionsInput | string[]
}



export type InstructionSetSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pathId?: boolean
  descriptiveInstructions?: boolean
  conciseInstructions?: boolean
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}, ExtArgs["result"]["instructionSet"]>

export type InstructionSetSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pathId?: boolean
  descriptiveInstructions?: boolean
  conciseInstructions?: boolean
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}, ExtArgs["result"]["instructionSet"]>

export type InstructionSetSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  pathId?: boolean
  descriptiveInstructions?: boolean
  conciseInstructions?: boolean
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}, ExtArgs["result"]["instructionSet"]>

export type InstructionSetSelectScalar = {
  id?: boolean
  pathId?: boolean
  descriptiveInstructions?: boolean
  conciseInstructions?: boolean
}

export type InstructionSetOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "pathId" | "descriptiveInstructions" | "conciseInstructions", ExtArgs["result"]["instructionSet"]>
export type InstructionSetInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}
export type InstructionSetIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}
export type InstructionSetIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}

export type $InstructionSetPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "InstructionSet"
  objects: {
    path: Prisma.$PathPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    pathId: string
    descriptiveInstructions: string[]
    conciseInstructions: string[]
  }, ExtArgs["result"]["instructionSet"]>
  composites: {}
}

export type InstructionSetGetPayload<S extends boolean | null | undefined | InstructionSetDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload, S>

export type InstructionSetCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<InstructionSetFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: InstructionSetCountAggregateInputType | true
  }

export interface InstructionSetDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['InstructionSet'], meta: { name: 'InstructionSet' } }
  /**
   * Find zero or one InstructionSet that matches the filter.
   * @param {InstructionSetFindUniqueArgs} args - Arguments to find a InstructionSet
   * @example
   * // Get one InstructionSet
   * const instructionSet = await prisma.instructionSet.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends InstructionSetFindUniqueArgs>(args: Prisma.SelectSubset<T, InstructionSetFindUniqueArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one InstructionSet that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {InstructionSetFindUniqueOrThrowArgs} args - Arguments to find a InstructionSet
   * @example
   * // Get one InstructionSet
   * const instructionSet = await prisma.instructionSet.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends InstructionSetFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, InstructionSetFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InstructionSet that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstructionSetFindFirstArgs} args - Arguments to find a InstructionSet
   * @example
   * // Get one InstructionSet
   * const instructionSet = await prisma.instructionSet.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends InstructionSetFindFirstArgs>(args?: Prisma.SelectSubset<T, InstructionSetFindFirstArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first InstructionSet that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstructionSetFindFirstOrThrowArgs} args - Arguments to find a InstructionSet
   * @example
   * // Get one InstructionSet
   * const instructionSet = await prisma.instructionSet.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends InstructionSetFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, InstructionSetFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more InstructionSets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstructionSetFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all InstructionSets
   * const instructionSets = await prisma.instructionSet.findMany()
   * 
   * // Get first 10 InstructionSets
   * const instructionSets = await prisma.instructionSet.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const instructionSetWithIdOnly = await prisma.instructionSet.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends InstructionSetFindManyArgs>(args?: Prisma.SelectSubset<T, InstructionSetFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a InstructionSet.
   * @param {InstructionSetCreateArgs} args - Arguments to create a InstructionSet.
   * @example
   * // Create one InstructionSet
   * const InstructionSet = await prisma.instructionSet.create({
   *   data: {
   *     // ... data to create a InstructionSet
   *   }
   * })
   * 
   */
  create<T extends InstructionSetCreateArgs>(args: Prisma.SelectSubset<T, InstructionSetCreateArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many InstructionSets.
   * @param {InstructionSetCreateManyArgs} args - Arguments to create many InstructionSets.
   * @example
   * // Create many InstructionSets
   * const instructionSet = await prisma.instructionSet.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends InstructionSetCreateManyArgs>(args?: Prisma.SelectSubset<T, InstructionSetCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many InstructionSets and returns the data saved in the database.
   * @param {InstructionSetCreateManyAndReturnArgs} args - Arguments to create many InstructionSets.
   * @example
   * // Create many InstructionSets
   * const instructionSet = await prisma.instructionSet.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many InstructionSets and only return the `id`
   * const instructionSetWithIdOnly = await prisma.instructionSet.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends InstructionSetCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, InstructionSetCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a InstructionSet.
   * @param {InstructionSetDeleteArgs} args - Arguments to delete one InstructionSet.
   * @example
   * // Delete one InstructionSet
   * const InstructionSet = await prisma.instructionSet.delete({
   *   where: {
   *     // ... filter to delete one InstructionSet
   *   }
   * })
   * 
   */
  delete<T extends InstructionSetDeleteArgs>(args: Prisma.SelectSubset<T, InstructionSetDeleteArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one InstructionSet.
   * @param {InstructionSetUpdateArgs} args - Arguments to update one InstructionSet.
   * @example
   * // Update one InstructionSet
   * const instructionSet = await prisma.instructionSet.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends InstructionSetUpdateArgs>(args: Prisma.SelectSubset<T, InstructionSetUpdateArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more InstructionSets.
   * @param {InstructionSetDeleteManyArgs} args - Arguments to filter InstructionSets to delete.
   * @example
   * // Delete a few InstructionSets
   * const { count } = await prisma.instructionSet.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends InstructionSetDeleteManyArgs>(args?: Prisma.SelectSubset<T, InstructionSetDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InstructionSets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstructionSetUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many InstructionSets
   * const instructionSet = await prisma.instructionSet.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends InstructionSetUpdateManyArgs>(args: Prisma.SelectSubset<T, InstructionSetUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more InstructionSets and returns the data updated in the database.
   * @param {InstructionSetUpdateManyAndReturnArgs} args - Arguments to update many InstructionSets.
   * @example
   * // Update many InstructionSets
   * const instructionSet = await prisma.instructionSet.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more InstructionSets and only return the `id`
   * const instructionSetWithIdOnly = await prisma.instructionSet.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends InstructionSetUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, InstructionSetUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one InstructionSet.
   * @param {InstructionSetUpsertArgs} args - Arguments to update or create a InstructionSet.
   * @example
   * // Update or create a InstructionSet
   * const instructionSet = await prisma.instructionSet.upsert({
   *   create: {
   *     // ... data to create a InstructionSet
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the InstructionSet we want to update
   *   }
   * })
   */
  upsert<T extends InstructionSetUpsertArgs>(args: Prisma.SelectSubset<T, InstructionSetUpsertArgs<ExtArgs>>): Prisma.Prisma__InstructionSetClient<runtime.Types.Result.GetResult<Prisma.$InstructionSetPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of InstructionSets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstructionSetCountArgs} args - Arguments to filter InstructionSets to count.
   * @example
   * // Count the number of InstructionSets
   * const count = await prisma.instructionSet.count({
   *   where: {
   *     // ... the filter for the InstructionSets we want to count
   *   }
   * })
  **/
  count<T extends InstructionSetCountArgs>(
    args?: Prisma.Subset<T, InstructionSetCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], InstructionSetCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a InstructionSet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstructionSetAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends InstructionSetAggregateArgs>(args: Prisma.Subset<T, InstructionSetAggregateArgs>): Prisma.PrismaPromise<GetInstructionSetAggregateType<T>>

  /**
   * Group by InstructionSet.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {InstructionSetGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends InstructionSetGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: InstructionSetGroupByArgs['orderBy'] }
      : { orderBy?: InstructionSetGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, InstructionSetGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetInstructionSetGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the InstructionSet model
 */
readonly fields: InstructionSetFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for InstructionSet.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__InstructionSetClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  path<T extends Prisma.PathDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PathDefaultArgs<ExtArgs>>): Prisma.Prisma__PathClient<runtime.Types.Result.GetResult<Prisma.$PathPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the InstructionSet model
 */
export interface InstructionSetFieldRefs {
  readonly id: Prisma.FieldRef<"InstructionSet", 'String'>
  readonly pathId: Prisma.FieldRef<"InstructionSet", 'String'>
  readonly descriptiveInstructions: Prisma.FieldRef<"InstructionSet", 'String[]'>
  readonly conciseInstructions: Prisma.FieldRef<"InstructionSet", 'String[]'>
}
    

// Custom InputTypes
/**
 * InstructionSet findUnique
 */
export type InstructionSetFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * Filter, which InstructionSet to fetch.
   */
  where: Prisma.InstructionSetWhereUniqueInput
}

/**
 * InstructionSet findUniqueOrThrow
 */
export type InstructionSetFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * Filter, which InstructionSet to fetch.
   */
  where: Prisma.InstructionSetWhereUniqueInput
}

/**
 * InstructionSet findFirst
 */
export type InstructionSetFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * Filter, which InstructionSet to fetch.
   */
  where?: Prisma.InstructionSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstructionSets to fetch.
   */
  orderBy?: Prisma.InstructionSetOrderByWithRelationInput | Prisma.InstructionSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InstructionSets.
   */
  cursor?: Prisma.InstructionSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstructionSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstructionSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InstructionSets.
   */
  distinct?: Prisma.InstructionSetScalarFieldEnum | Prisma.InstructionSetScalarFieldEnum[]
}

/**
 * InstructionSet findFirstOrThrow
 */
export type InstructionSetFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * Filter, which InstructionSet to fetch.
   */
  where?: Prisma.InstructionSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstructionSets to fetch.
   */
  orderBy?: Prisma.InstructionSetOrderByWithRelationInput | Prisma.InstructionSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for InstructionSets.
   */
  cursor?: Prisma.InstructionSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstructionSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstructionSets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of InstructionSets.
   */
  distinct?: Prisma.InstructionSetScalarFieldEnum | Prisma.InstructionSetScalarFieldEnum[]
}

/**
 * InstructionSet findMany
 */
export type InstructionSetFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * Filter, which InstructionSets to fetch.
   */
  where?: Prisma.InstructionSetWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of InstructionSets to fetch.
   */
  orderBy?: Prisma.InstructionSetOrderByWithRelationInput | Prisma.InstructionSetOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing InstructionSets.
   */
  cursor?: Prisma.InstructionSetWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` InstructionSets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` InstructionSets.
   */
  skip?: number
  distinct?: Prisma.InstructionSetScalarFieldEnum | Prisma.InstructionSetScalarFieldEnum[]
}

/**
 * InstructionSet create
 */
export type InstructionSetCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * The data needed to create a InstructionSet.
   */
  data: Prisma.XOR<Prisma.InstructionSetCreateInput, Prisma.InstructionSetUncheckedCreateInput>
}

/**
 * InstructionSet createMany
 */
export type InstructionSetCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many InstructionSets.
   */
  data: Prisma.InstructionSetCreateManyInput | Prisma.InstructionSetCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * InstructionSet createManyAndReturn
 */
export type InstructionSetCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * The data used to create many InstructionSets.
   */
  data: Prisma.InstructionSetCreateManyInput | Prisma.InstructionSetCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * InstructionSet update
 */
export type InstructionSetUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * The data needed to update a InstructionSet.
   */
  data: Prisma.XOR<Prisma.InstructionSetUpdateInput, Prisma.InstructionSetUncheckedUpdateInput>
  /**
   * Choose, which InstructionSet to update.
   */
  where: Prisma.InstructionSetWhereUniqueInput
}

/**
 * InstructionSet updateMany
 */
export type InstructionSetUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update InstructionSets.
   */
  data: Prisma.XOR<Prisma.InstructionSetUpdateManyMutationInput, Prisma.InstructionSetUncheckedUpdateManyInput>
  /**
   * Filter which InstructionSets to update
   */
  where?: Prisma.InstructionSetWhereInput
  /**
   * Limit how many InstructionSets to update.
   */
  limit?: number
}

/**
 * InstructionSet updateManyAndReturn
 */
export type InstructionSetUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * The data used to update InstructionSets.
   */
  data: Prisma.XOR<Prisma.InstructionSetUpdateManyMutationInput, Prisma.InstructionSetUncheckedUpdateManyInput>
  /**
   * Filter which InstructionSets to update
   */
  where?: Prisma.InstructionSetWhereInput
  /**
   * Limit how many InstructionSets to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * InstructionSet upsert
 */
export type InstructionSetUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * The filter to search for the InstructionSet to update in case it exists.
   */
  where: Prisma.InstructionSetWhereUniqueInput
  /**
   * In case the InstructionSet found by the `where` argument doesn't exist, create a new InstructionSet with this data.
   */
  create: Prisma.XOR<Prisma.InstructionSetCreateInput, Prisma.InstructionSetUncheckedCreateInput>
  /**
   * In case the InstructionSet was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.InstructionSetUpdateInput, Prisma.InstructionSetUncheckedUpdateInput>
}

/**
 * InstructionSet delete
 */
export type InstructionSetDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
  /**
   * Filter which InstructionSet to delete.
   */
  where: Prisma.InstructionSetWhereUniqueInput
}

/**
 * InstructionSet deleteMany
 */
export type InstructionSetDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which InstructionSets to delete
   */
  where?: Prisma.InstructionSetWhereInput
  /**
   * Limit how many InstructionSets to delete.
   */
  limit?: number
}

/**
 * InstructionSet without action
 */
export type InstructionSetDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the InstructionSet
   */
  select?: Prisma.InstructionSetSelect<ExtArgs> | null
  /**
   * Omit specific fields from the InstructionSet
   */
  omit?: Prisma.InstructionSetOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.InstructionSetInclude<ExtArgs> | null
}
