
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `PathAnchor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PathAnchor
 * 
 */
export type PathAnchorModel = runtime.Types.Result.DefaultSelection<Prisma.$PathAnchorPayload>

export type AggregatePathAnchor = {
  _count: PathAnchorCountAggregateOutputType | null
  _avg: PathAnchorAvgAggregateOutputType | null
  _sum: PathAnchorSumAggregateOutputType | null
  _min: PathAnchorMinAggregateOutputType | null
  _max: PathAnchorMaxAggregateOutputType | null
}

export type PathAnchorAvgAggregateOutputType = {
  index: number | null
  xCoords: number | null
  yCoords: number | null
}

export type PathAnchorSumAggregateOutputType = {
  index: number | null
  xCoords: number | null
  yCoords: number | null
}

export type PathAnchorMinAggregateOutputType = {
  id: string | null
  index: number | null
  xCoords: number | null
  yCoords: number | null
  pathId: string | null
}

export type PathAnchorMaxAggregateOutputType = {
  id: string | null
  index: number | null
  xCoords: number | null
  yCoords: number | null
  pathId: string | null
}

export type PathAnchorCountAggregateOutputType = {
  id: number
  index: number
  xCoords: number
  yCoords: number
  pathId: number
  _all: number
}


export type PathAnchorAvgAggregateInputType = {
  index?: true
  xCoords?: true
  yCoords?: true
}

export type PathAnchorSumAggregateInputType = {
  index?: true
  xCoords?: true
  yCoords?: true
}

export type PathAnchorMinAggregateInputType = {
  id?: true
  index?: true
  xCoords?: true
  yCoords?: true
  pathId?: true
}

export type PathAnchorMaxAggregateInputType = {
  id?: true
  index?: true
  xCoords?: true
  yCoords?: true
  pathId?: true
}

export type PathAnchorCountAggregateInputType = {
  id?: true
  index?: true
  xCoords?: true
  yCoords?: true
  pathId?: true
  _all?: true
}

export type PathAnchorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PathAnchor to aggregate.
   */
  where?: Prisma.PathAnchorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathAnchors to fetch.
   */
  orderBy?: Prisma.PathAnchorOrderByWithRelationInput | Prisma.PathAnchorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PathAnchorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathAnchors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathAnchors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PathAnchors
  **/
  _count?: true | PathAnchorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PathAnchorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PathAnchorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PathAnchorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PathAnchorMaxAggregateInputType
}

export type GetPathAnchorAggregateType<T extends PathAnchorAggregateArgs> = {
      [P in keyof T & keyof AggregatePathAnchor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePathAnchor[P]>
    : Prisma.GetScalarType<T[P], AggregatePathAnchor[P]>
}




export type PathAnchorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PathAnchorWhereInput
  orderBy?: Prisma.PathAnchorOrderByWithAggregationInput | Prisma.PathAnchorOrderByWithAggregationInput[]
  by: Prisma.PathAnchorScalarFieldEnum[] | Prisma.PathAnchorScalarFieldEnum
  having?: Prisma.PathAnchorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PathAnchorCountAggregateInputType | true
  _avg?: PathAnchorAvgAggregateInputType
  _sum?: PathAnchorSumAggregateInputType
  _min?: PathAnchorMinAggregateInputType
  _max?: PathAnchorMaxAggregateInputType
}

export type PathAnchorGroupByOutputType = {
  id: string
  index: number
  xCoords: number
  yCoords: number
  pathId: string
  _count: PathAnchorCountAggregateOutputType | null
  _avg: PathAnchorAvgAggregateOutputType | null
  _sum: PathAnchorSumAggregateOutputType | null
  _min: PathAnchorMinAggregateOutputType | null
  _max: PathAnchorMaxAggregateOutputType | null
}

type GetPathAnchorGroupByPayload<T extends PathAnchorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PathAnchorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PathAnchorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PathAnchorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PathAnchorGroupByOutputType[P]>
      }
    >
  >



export type PathAnchorWhereInput = {
  AND?: Prisma.PathAnchorWhereInput | Prisma.PathAnchorWhereInput[]
  OR?: Prisma.PathAnchorWhereInput[]
  NOT?: Prisma.PathAnchorWhereInput | Prisma.PathAnchorWhereInput[]
  id?: Prisma.StringFilter<"PathAnchor"> | string
  index?: Prisma.IntFilter<"PathAnchor"> | number
  xCoords?: Prisma.FloatFilter<"PathAnchor"> | number
  yCoords?: Prisma.FloatFilter<"PathAnchor"> | number
  pathId?: Prisma.StringFilter<"PathAnchor"> | string
  path?: Prisma.XOR<Prisma.PathScalarRelationFilter, Prisma.PathWhereInput>
}

export type PathAnchorOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  xCoords?: Prisma.SortOrder
  yCoords?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
  path?: Prisma.PathOrderByWithRelationInput
}

export type PathAnchorWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PathAnchorWhereInput | Prisma.PathAnchorWhereInput[]
  OR?: Prisma.PathAnchorWhereInput[]
  NOT?: Prisma.PathAnchorWhereInput | Prisma.PathAnchorWhereInput[]
  index?: Prisma.IntFilter<"PathAnchor"> | number
  xCoords?: Prisma.FloatFilter<"PathAnchor"> | number
  yCoords?: Prisma.FloatFilter<"PathAnchor"> | number
  pathId?: Prisma.StringFilter<"PathAnchor"> | string
  path?: Prisma.XOR<Prisma.PathScalarRelationFilter, Prisma.PathWhereInput>
}, "id">

export type PathAnchorOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  xCoords?: Prisma.SortOrder
  yCoords?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
  _count?: Prisma.PathAnchorCountOrderByAggregateInput
  _avg?: Prisma.PathAnchorAvgOrderByAggregateInput
  _max?: Prisma.PathAnchorMaxOrderByAggregateInput
  _min?: Prisma.PathAnchorMinOrderByAggregateInput
  _sum?: Prisma.PathAnchorSumOrderByAggregateInput
}

export type PathAnchorScalarWhereWithAggregatesInput = {
  AND?: Prisma.PathAnchorScalarWhereWithAggregatesInput | Prisma.PathAnchorScalarWhereWithAggregatesInput[]
  OR?: Prisma.PathAnchorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PathAnchorScalarWhereWithAggregatesInput | Prisma.PathAnchorScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PathAnchor"> | string
  index?: Prisma.IntWithAggregatesFilter<"PathAnchor"> | number
  xCoords?: Prisma.FloatWithAggregatesFilter<"PathAnchor"> | number
  yCoords?: Prisma.FloatWithAggregatesFilter<"PathAnchor"> | number
  pathId?: Prisma.StringWithAggregatesFilter<"PathAnchor"> | string
}

export type PathAnchorCreateInput = {
  id?: string
  index: number
  xCoords: number
  yCoords: number
  path: Prisma.PathCreateNestedOneWithoutAnchorsInput
}

export type PathAnchorUncheckedCreateInput = {
  id?: string
  index: number
  xCoords: number
  yCoords: number
  pathId: string
}

export type PathAnchorUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  xCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  yCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  path?: Prisma.PathUpdateOneRequiredWithoutAnchorsNestedInput
}

export type PathAnchorUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  xCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  yCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  pathId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PathAnchorCreateManyInput = {
  id?: string
  index: number
  xCoords: number
  yCoords: number
  pathId: string
}

export type PathAnchorUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  xCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  yCoords?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PathAnchorUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  xCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  yCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  pathId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PathAnchorListRelationFilter = {
  every?: Prisma.PathAnchorWhereInput
  some?: Prisma.PathAnchorWhereInput
  none?: Prisma.PathAnchorWhereInput
}

export type PathAnchorOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PathAnchorCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  xCoords?: Prisma.SortOrder
  yCoords?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
}

export type PathAnchorAvgOrderByAggregateInput = {
  index?: Prisma.SortOrder
  xCoords?: Prisma.SortOrder
  yCoords?: Prisma.SortOrder
}

export type PathAnchorMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  xCoords?: Prisma.SortOrder
  yCoords?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
}

export type PathAnchorMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  index?: Prisma.SortOrder
  xCoords?: Prisma.SortOrder
  yCoords?: Prisma.SortOrder
  pathId?: Prisma.SortOrder
}

export type PathAnchorSumOrderByAggregateInput = {
  index?: Prisma.SortOrder
  xCoords?: Prisma.SortOrder
  yCoords?: Prisma.SortOrder
}

export type PathAnchorCreateNestedManyWithoutPathInput = {
  create?: Prisma.XOR<Prisma.PathAnchorCreateWithoutPathInput, Prisma.PathAnchorUncheckedCreateWithoutPathInput> | Prisma.PathAnchorCreateWithoutPathInput[] | Prisma.PathAnchorUncheckedCreateWithoutPathInput[]
  connectOrCreate?: Prisma.PathAnchorCreateOrConnectWithoutPathInput | Prisma.PathAnchorCreateOrConnectWithoutPathInput[]
  createMany?: Prisma.PathAnchorCreateManyPathInputEnvelope
  connect?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
}

export type PathAnchorUncheckedCreateNestedManyWithoutPathInput = {
  create?: Prisma.XOR<Prisma.PathAnchorCreateWithoutPathInput, Prisma.PathAnchorUncheckedCreateWithoutPathInput> | Prisma.PathAnchorCreateWithoutPathInput[] | Prisma.PathAnchorUncheckedCreateWithoutPathInput[]
  connectOrCreate?: Prisma.PathAnchorCreateOrConnectWithoutPathInput | Prisma.PathAnchorCreateOrConnectWithoutPathInput[]
  createMany?: Prisma.PathAnchorCreateManyPathInputEnvelope
  connect?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
}

export type PathAnchorUpdateManyWithoutPathNestedInput = {
  create?: Prisma.XOR<Prisma.PathAnchorCreateWithoutPathInput, Prisma.PathAnchorUncheckedCreateWithoutPathInput> | Prisma.PathAnchorCreateWithoutPathInput[] | Prisma.PathAnchorUncheckedCreateWithoutPathInput[]
  connectOrCreate?: Prisma.PathAnchorCreateOrConnectWithoutPathInput | Prisma.PathAnchorCreateOrConnectWithoutPathInput[]
  upsert?: Prisma.PathAnchorUpsertWithWhereUniqueWithoutPathInput | Prisma.PathAnchorUpsertWithWhereUniqueWithoutPathInput[]
  createMany?: Prisma.PathAnchorCreateManyPathInputEnvelope
  set?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  disconnect?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  delete?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  connect?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  update?: Prisma.PathAnchorUpdateWithWhereUniqueWithoutPathInput | Prisma.PathAnchorUpdateWithWhereUniqueWithoutPathInput[]
  updateMany?: Prisma.PathAnchorUpdateManyWithWhereWithoutPathInput | Prisma.PathAnchorUpdateManyWithWhereWithoutPathInput[]
  deleteMany?: Prisma.PathAnchorScalarWhereInput | Prisma.PathAnchorScalarWhereInput[]
}

export type PathAnchorUncheckedUpdateManyWithoutPathNestedInput = {
  create?: Prisma.XOR<Prisma.PathAnchorCreateWithoutPathInput, Prisma.PathAnchorUncheckedCreateWithoutPathInput> | Prisma.PathAnchorCreateWithoutPathInput[] | Prisma.PathAnchorUncheckedCreateWithoutPathInput[]
  connectOrCreate?: Prisma.PathAnchorCreateOrConnectWithoutPathInput | Prisma.PathAnchorCreateOrConnectWithoutPathInput[]
  upsert?: Prisma.PathAnchorUpsertWithWhereUniqueWithoutPathInput | Prisma.PathAnchorUpsertWithWhereUniqueWithoutPathInput[]
  createMany?: Prisma.PathAnchorCreateManyPathInputEnvelope
  set?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  disconnect?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  delete?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  connect?: Prisma.PathAnchorWhereUniqueInput | Prisma.PathAnchorWhereUniqueInput[]
  update?: Prisma.PathAnchorUpdateWithWhereUniqueWithoutPathInput | Prisma.PathAnchorUpdateWithWhereUniqueWithoutPathInput[]
  updateMany?: Prisma.PathAnchorUpdateManyWithWhereWithoutPathInput | Prisma.PathAnchorUpdateManyWithWhereWithoutPathInput[]
  deleteMany?: Prisma.PathAnchorScalarWhereInput | Prisma.PathAnchorScalarWhereInput[]
}

export type PathAnchorCreateWithoutPathInput = {
  id?: string
  index: number
  xCoords: number
  yCoords: number
}

export type PathAnchorUncheckedCreateWithoutPathInput = {
  id?: string
  index: number
  xCoords: number
  yCoords: number
}

export type PathAnchorCreateOrConnectWithoutPathInput = {
  where: Prisma.PathAnchorWhereUniqueInput
  create: Prisma.XOR<Prisma.PathAnchorCreateWithoutPathInput, Prisma.PathAnchorUncheckedCreateWithoutPathInput>
}

export type PathAnchorCreateManyPathInputEnvelope = {
  data: Prisma.PathAnchorCreateManyPathInput | Prisma.PathAnchorCreateManyPathInput[]
  skipDuplicates?: boolean
}

export type PathAnchorUpsertWithWhereUniqueWithoutPathInput = {
  where: Prisma.PathAnchorWhereUniqueInput
  update: Prisma.XOR<Prisma.PathAnchorUpdateWithoutPathInput, Prisma.PathAnchorUncheckedUpdateWithoutPathInput>
  create: Prisma.XOR<Prisma.PathAnchorCreateWithoutPathInput, Prisma.PathAnchorUncheckedCreateWithoutPathInput>
}

export type PathAnchorUpdateWithWhereUniqueWithoutPathInput = {
  where: Prisma.PathAnchorWhereUniqueInput
  data: Prisma.XOR<Prisma.PathAnchorUpdateWithoutPathInput, Prisma.PathAnchorUncheckedUpdateWithoutPathInput>
}

export type PathAnchorUpdateManyWithWhereWithoutPathInput = {
  where: Prisma.PathAnchorScalarWhereInput
  data: Prisma.XOR<Prisma.PathAnchorUpdateManyMutationInput, Prisma.PathAnchorUncheckedUpdateManyWithoutPathInput>
}

export type PathAnchorScalarWhereInput = {
  AND?: Prisma.PathAnchorScalarWhereInput | Prisma.PathAnchorScalarWhereInput[]
  OR?: Prisma.PathAnchorScalarWhereInput[]
  NOT?: Prisma.PathAnchorScalarWhereInput | Prisma.PathAnchorScalarWhereInput[]
  id?: Prisma.StringFilter<"PathAnchor"> | string
  index?: Prisma.IntFilter<"PathAnchor"> | number
  xCoords?: Prisma.FloatFilter<"PathAnchor"> | number
  yCoords?: Prisma.FloatFilter<"PathAnchor"> | number
  pathId?: Prisma.StringFilter<"PathAnchor"> | string
}

export type PathAnchorCreateManyPathInput = {
  id?: string
  index: number
  xCoords: number
  yCoords: number
}

export type PathAnchorUpdateWithoutPathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  xCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  yCoords?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PathAnchorUncheckedUpdateWithoutPathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  xCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  yCoords?: Prisma.FloatFieldUpdateOperationsInput | number
}

export type PathAnchorUncheckedUpdateManyWithoutPathInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  index?: Prisma.IntFieldUpdateOperationsInput | number
  xCoords?: Prisma.FloatFieldUpdateOperationsInput | number
  yCoords?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type PathAnchorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  index?: boolean
  xCoords?: boolean
  yCoords?: boolean
  pathId?: boolean
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pathAnchor"]>

export type PathAnchorSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  index?: boolean
  xCoords?: boolean
  yCoords?: boolean
  pathId?: boolean
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pathAnchor"]>

export type PathAnchorSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  index?: boolean
  xCoords?: boolean
  yCoords?: boolean
  pathId?: boolean
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}, ExtArgs["result"]["pathAnchor"]>

export type PathAnchorSelectScalar = {
  id?: boolean
  index?: boolean
  xCoords?: boolean
  yCoords?: boolean
  pathId?: boolean
}

export type PathAnchorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "index" | "xCoords" | "yCoords" | "pathId", ExtArgs["result"]["pathAnchor"]>
export type PathAnchorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}
export type PathAnchorIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}
export type PathAnchorIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  path?: boolean | Prisma.PathDefaultArgs<ExtArgs>
}

export type $PathAnchorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PathAnchor"
  objects: {
    path: Prisma.$PathPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    index: number
    xCoords: number
    yCoords: number
    pathId: string
  }, ExtArgs["result"]["pathAnchor"]>
  composites: {}
}

export type PathAnchorGetPayload<S extends boolean | null | undefined | PathAnchorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload, S>

export type PathAnchorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PathAnchorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PathAnchorCountAggregateInputType | true
  }

export interface PathAnchorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PathAnchor'], meta: { name: 'PathAnchor' } }
  /**
   * Find zero or one PathAnchor that matches the filter.
   * @param {PathAnchorFindUniqueArgs} args - Arguments to find a PathAnchor
   * @example
   * // Get one PathAnchor
   * const pathAnchor = await prisma.pathAnchor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PathAnchorFindUniqueArgs>(args: Prisma.SelectSubset<T, PathAnchorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PathAnchor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PathAnchorFindUniqueOrThrowArgs} args - Arguments to find a PathAnchor
   * @example
   * // Get one PathAnchor
   * const pathAnchor = await prisma.pathAnchor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PathAnchorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PathAnchorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PathAnchor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathAnchorFindFirstArgs} args - Arguments to find a PathAnchor
   * @example
   * // Get one PathAnchor
   * const pathAnchor = await prisma.pathAnchor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PathAnchorFindFirstArgs>(args?: Prisma.SelectSubset<T, PathAnchorFindFirstArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PathAnchor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathAnchorFindFirstOrThrowArgs} args - Arguments to find a PathAnchor
   * @example
   * // Get one PathAnchor
   * const pathAnchor = await prisma.pathAnchor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PathAnchorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PathAnchorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PathAnchors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathAnchorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PathAnchors
   * const pathAnchors = await prisma.pathAnchor.findMany()
   * 
   * // Get first 10 PathAnchors
   * const pathAnchors = await prisma.pathAnchor.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const pathAnchorWithIdOnly = await prisma.pathAnchor.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PathAnchorFindManyArgs>(args?: Prisma.SelectSubset<T, PathAnchorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PathAnchor.
   * @param {PathAnchorCreateArgs} args - Arguments to create a PathAnchor.
   * @example
   * // Create one PathAnchor
   * const PathAnchor = await prisma.pathAnchor.create({
   *   data: {
   *     // ... data to create a PathAnchor
   *   }
   * })
   * 
   */
  create<T extends PathAnchorCreateArgs>(args: Prisma.SelectSubset<T, PathAnchorCreateArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PathAnchors.
   * @param {PathAnchorCreateManyArgs} args - Arguments to create many PathAnchors.
   * @example
   * // Create many PathAnchors
   * const pathAnchor = await prisma.pathAnchor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PathAnchorCreateManyArgs>(args?: Prisma.SelectSubset<T, PathAnchorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PathAnchors and returns the data saved in the database.
   * @param {PathAnchorCreateManyAndReturnArgs} args - Arguments to create many PathAnchors.
   * @example
   * // Create many PathAnchors
   * const pathAnchor = await prisma.pathAnchor.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PathAnchors and only return the `id`
   * const pathAnchorWithIdOnly = await prisma.pathAnchor.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PathAnchorCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PathAnchorCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PathAnchor.
   * @param {PathAnchorDeleteArgs} args - Arguments to delete one PathAnchor.
   * @example
   * // Delete one PathAnchor
   * const PathAnchor = await prisma.pathAnchor.delete({
   *   where: {
   *     // ... filter to delete one PathAnchor
   *   }
   * })
   * 
   */
  delete<T extends PathAnchorDeleteArgs>(args: Prisma.SelectSubset<T, PathAnchorDeleteArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PathAnchor.
   * @param {PathAnchorUpdateArgs} args - Arguments to update one PathAnchor.
   * @example
   * // Update one PathAnchor
   * const pathAnchor = await prisma.pathAnchor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PathAnchorUpdateArgs>(args: Prisma.SelectSubset<T, PathAnchorUpdateArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PathAnchors.
   * @param {PathAnchorDeleteManyArgs} args - Arguments to filter PathAnchors to delete.
   * @example
   * // Delete a few PathAnchors
   * const { count } = await prisma.pathAnchor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PathAnchorDeleteManyArgs>(args?: Prisma.SelectSubset<T, PathAnchorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PathAnchors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathAnchorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PathAnchors
   * const pathAnchor = await prisma.pathAnchor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PathAnchorUpdateManyArgs>(args: Prisma.SelectSubset<T, PathAnchorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PathAnchors and returns the data updated in the database.
   * @param {PathAnchorUpdateManyAndReturnArgs} args - Arguments to update many PathAnchors.
   * @example
   * // Update many PathAnchors
   * const pathAnchor = await prisma.pathAnchor.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PathAnchors and only return the `id`
   * const pathAnchorWithIdOnly = await prisma.pathAnchor.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PathAnchorUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PathAnchorUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PathAnchor.
   * @param {PathAnchorUpsertArgs} args - Arguments to update or create a PathAnchor.
   * @example
   * // Update or create a PathAnchor
   * const pathAnchor = await prisma.pathAnchor.upsert({
   *   create: {
   *     // ... data to create a PathAnchor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PathAnchor we want to update
   *   }
   * })
   */
  upsert<T extends PathAnchorUpsertArgs>(args: Prisma.SelectSubset<T, PathAnchorUpsertArgs<ExtArgs>>): Prisma.Prisma__PathAnchorClient<runtime.Types.Result.GetResult<Prisma.$PathAnchorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PathAnchors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathAnchorCountArgs} args - Arguments to filter PathAnchors to count.
   * @example
   * // Count the number of PathAnchors
   * const count = await prisma.pathAnchor.count({
   *   where: {
   *     // ... the filter for the PathAnchors we want to count
   *   }
   * })
  **/
  count<T extends PathAnchorCountArgs>(
    args?: Prisma.Subset<T, PathAnchorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PathAnchorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PathAnchor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathAnchorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PathAnchorAggregateArgs>(args: Prisma.Subset<T, PathAnchorAggregateArgs>): Prisma.PrismaPromise<GetPathAnchorAggregateType<T>>

  /**
   * Group by PathAnchor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PathAnchorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PathAnchorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PathAnchorGroupByArgs['orderBy'] }
      : { orderBy?: PathAnchorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PathAnchorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPathAnchorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PathAnchor model
 */
readonly fields: PathAnchorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PathAnchor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PathAnchorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  path<T extends Prisma.PathDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PathDefaultArgs<ExtArgs>>): Prisma.Prisma__PathClient<runtime.Types.Result.GetResult<Prisma.$PathPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PathAnchor model
 */
export interface PathAnchorFieldRefs {
  readonly id: Prisma.FieldRef<"PathAnchor", 'String'>
  readonly index: Prisma.FieldRef<"PathAnchor", 'Int'>
  readonly xCoords: Prisma.FieldRef<"PathAnchor", 'Float'>
  readonly yCoords: Prisma.FieldRef<"PathAnchor", 'Float'>
  readonly pathId: Prisma.FieldRef<"PathAnchor", 'String'>
}
    

// Custom InputTypes
/**
 * PathAnchor findUnique
 */
export type PathAnchorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * Filter, which PathAnchor to fetch.
   */
  where: Prisma.PathAnchorWhereUniqueInput
}

/**
 * PathAnchor findUniqueOrThrow
 */
export type PathAnchorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * Filter, which PathAnchor to fetch.
   */
  where: Prisma.PathAnchorWhereUniqueInput
}

/**
 * PathAnchor findFirst
 */
export type PathAnchorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * Filter, which PathAnchor to fetch.
   */
  where?: Prisma.PathAnchorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathAnchors to fetch.
   */
  orderBy?: Prisma.PathAnchorOrderByWithRelationInput | Prisma.PathAnchorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PathAnchors.
   */
  cursor?: Prisma.PathAnchorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathAnchors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathAnchors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PathAnchors.
   */
  distinct?: Prisma.PathAnchorScalarFieldEnum | Prisma.PathAnchorScalarFieldEnum[]
}

/**
 * PathAnchor findFirstOrThrow
 */
export type PathAnchorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * Filter, which PathAnchor to fetch.
   */
  where?: Prisma.PathAnchorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathAnchors to fetch.
   */
  orderBy?: Prisma.PathAnchorOrderByWithRelationInput | Prisma.PathAnchorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PathAnchors.
   */
  cursor?: Prisma.PathAnchorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathAnchors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathAnchors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PathAnchors.
   */
  distinct?: Prisma.PathAnchorScalarFieldEnum | Prisma.PathAnchorScalarFieldEnum[]
}

/**
 * PathAnchor findMany
 */
export type PathAnchorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * Filter, which PathAnchors to fetch.
   */
  where?: Prisma.PathAnchorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PathAnchors to fetch.
   */
  orderBy?: Prisma.PathAnchorOrderByWithRelationInput | Prisma.PathAnchorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PathAnchors.
   */
  cursor?: Prisma.PathAnchorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PathAnchors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PathAnchors.
   */
  skip?: number
  distinct?: Prisma.PathAnchorScalarFieldEnum | Prisma.PathAnchorScalarFieldEnum[]
}

/**
 * PathAnchor create
 */
export type PathAnchorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * The data needed to create a PathAnchor.
   */
  data: Prisma.XOR<Prisma.PathAnchorCreateInput, Prisma.PathAnchorUncheckedCreateInput>
}

/**
 * PathAnchor createMany
 */
export type PathAnchorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PathAnchors.
   */
  data: Prisma.PathAnchorCreateManyInput | Prisma.PathAnchorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PathAnchor createManyAndReturn
 */
export type PathAnchorCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * The data used to create many PathAnchors.
   */
  data: Prisma.PathAnchorCreateManyInput | Prisma.PathAnchorCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PathAnchor update
 */
export type PathAnchorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * The data needed to update a PathAnchor.
   */
  data: Prisma.XOR<Prisma.PathAnchorUpdateInput, Prisma.PathAnchorUncheckedUpdateInput>
  /**
   * Choose, which PathAnchor to update.
   */
  where: Prisma.PathAnchorWhereUniqueInput
}

/**
 * PathAnchor updateMany
 */
export type PathAnchorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PathAnchors.
   */
  data: Prisma.XOR<Prisma.PathAnchorUpdateManyMutationInput, Prisma.PathAnchorUncheckedUpdateManyInput>
  /**
   * Filter which PathAnchors to update
   */
  where?: Prisma.PathAnchorWhereInput
  /**
   * Limit how many PathAnchors to update.
   */
  limit?: number
}

/**
 * PathAnchor updateManyAndReturn
 */
export type PathAnchorUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * The data used to update PathAnchors.
   */
  data: Prisma.XOR<Prisma.PathAnchorUpdateManyMutationInput, Prisma.PathAnchorUncheckedUpdateManyInput>
  /**
   * Filter which PathAnchors to update
   */
  where?: Prisma.PathAnchorWhereInput
  /**
   * Limit how many PathAnchors to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PathAnchor upsert
 */
export type PathAnchorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * The filter to search for the PathAnchor to update in case it exists.
   */
  where: Prisma.PathAnchorWhereUniqueInput
  /**
   * In case the PathAnchor found by the `where` argument doesn't exist, create a new PathAnchor with this data.
   */
  create: Prisma.XOR<Prisma.PathAnchorCreateInput, Prisma.PathAnchorUncheckedCreateInput>
  /**
   * In case the PathAnchor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PathAnchorUpdateInput, Prisma.PathAnchorUncheckedUpdateInput>
}

/**
 * PathAnchor delete
 */
export type PathAnchorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
  /**
   * Filter which PathAnchor to delete.
   */
  where: Prisma.PathAnchorWhereUniqueInput
}

/**
 * PathAnchor deleteMany
 */
export type PathAnchorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PathAnchors to delete
   */
  where?: Prisma.PathAnchorWhereInput
  /**
   * Limit how many PathAnchors to delete.
   */
  limit?: number
}

/**
 * PathAnchor without action
 */
export type PathAnchorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PathAnchor
   */
  select?: Prisma.PathAnchorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PathAnchor
   */
  omit?: Prisma.PathAnchorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PathAnchorInclude<ExtArgs> | null
}
